### PR TITLE
Quotation-Card-and-Content-Styling

### PR DESCRIPTION
**Pull request by mishs**

### CODE REVIEW

**Comment by PiDelport** [comment]
@mishs: This looks like a mixture of changes… is there a description or card for the changes somewhere?

**Comment by mishs** [comment]
> @mishs: This looks like a mixture of changes… is there a description or card for the changes somewhere?

@PiDelport - these specific changes are verbal instructions from Matt. I think he is yet to create one.

**Comment by PiDelport** [comment]
@mishs: I updated this to fix src/components/Hero/styles.js which got changed to DOS line endings.

**Comment by PiDelport** [comment]
PR #15 should subsume this.

**Comment by PiDelport** [comment]
PR #15 should subsume this.

**Pull request closed without merging**
