### PR TITLE
Change wording from Protest Guide to Evictions guide

### PR DESCRIPTION
**Pull request by mishs**
Trello:

* https://trello.com/c/ECAA9lpF/10-update-repo-copy-protest-guide-%E2%86%92-eviction-process
* https://trello.com/c/joNJ17ba/19-media-icons-links-corresponding-to-evictions

### CODE REVIEW

**Comment by PiDelport** [comment]
Card: https://trello.com/c/ECAA9lpF/10-replace-copy-protest-guide-%E2%86%92-eviction-process

**Comment by PiDelport** [comment]
@mishs: Can we get all the changes for the card rolled into this branch / PR?

**Comment by PiDelport** [comment]
(@mishs: I did a quick drive-by rebase)

**Comment by mishs** [comment]
> A quick search for remaining protest guide occurrences:
> 
> ```
> package.json:2:  "name": "protest-guide",
> README.md:1:# Protest Guide &middot; stability-wip
> README.md:9:1. Clone this project by running `git clone https://github.com/OpenUpSA/protest-guide.git`.
> src/components/SpeedDial/index.jsx:16:    href: 'https://www.facebook.com/sharer/sharer.php?u=https%3A//protestguide.org.za/'
> src/components/SpeedDial/index.jsx:21:    href: 'https://twitter.com/home?status=https%3A//protestguide.org.za/'
> src/components/SpeedDial/index.jsx:26:    href: 'whatsapp://send?text=https://protestguide.org.za'
> package-lock.json:2:  "name": "protest-guide",
> ```

@PiDelport - changed the titles I could. As for the other ones pointing to media links- now waiting for links relating to Evictions. 
  Matching trello-card:  https://trello.com/c/joNJ17ba

**Comment by PiDelport** [comment]
Alright, I sat together with @mishs to go through these, and it should be good to go.

**Pull request merged**
